name: build vauthenticator management ui

on:
  push: { }
  workflow_dispatch: { }

jobs:
  provisioning:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install nodejs
        run: |
          sudo apt -y update
          sudo apt -y install nodejs
          sudo apt -y install npm

      - name: install openjdk
        run: |
          sudo apt-get update && sudo apt-get install openjdk-17-jdk
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
          java -version

      - name: build testing environment
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

          git clone https://github.com/mrFlick72/client-security-starter.git
          cd client-security-starter
          mvn clean install -q

      - name: build testing environment
        run: |
          git clone https://github.com/mrFlick72/aws-messaging-java-client.git
          cd aws-messaging-java-client
          mvn clean install

      - name: Build frontend artifacts
        run: |
          cd management-ui/src/main/frontend
          npm install
          npm run-script build

      - name: Build
        run: |
          cd management-ui
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          mvn install

      - name: docker push
        run: |
          cd management-ui
          if [[ ${GITHUB_REF##*/} == 'master' ]]
          then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${GITHUB_REF##*/}"
          fi
          echo "$DOCKER_TAG"
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build . -t mrflick72/vauthenticator-management-ui-k8s:$DOCKER_TAG
          docker push mrflick72/vauthenticator-management-ui-k8s:$DOCKER_TAG
